remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true

title: Setup Tutorial
# description: Intro to Programming

# primerSpec:
  # sitemap:
    # label: Docs & Demos
# defaultCodeblockVariant: no-line-numbers

sass:
  style: :compressed

exclude:
  - .bundle
  - .githooks
  - .github
  - .vscode
  - node_modules
  - script
  - src_js
  - .eslintrc
  - .prettierignore
  - .prettierrc
  - '*.yml'
  - '*.lock'
  - '*.config.js'
  - '*.code-workspace'
  - '*.ts'
  - '*.gem'
  - '*.gemspec'
  - Gemfile
  - package.json
  - package-lock.json
  - tsconfig.json
  - VERSION
  - vendor
